version: '3.7'
services:
  db:
    image: postgres:13.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=delivery
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
  ws:
    image: webservice
    build: .
    ports:
      - 8080:8080
    environment:
      - CATALINA_OPTS=-DJDBC_DATABASE_URL='jdbc:postgresql://db:5432/db?user=app&password=pass'
    depends_on:
      - db