-- DELETE
-- FROM users;
-- DELETE
-- FROM roles;
--
-- INSERT INTO roles(id, name)
-- VALUES (1, 'ADMIN');
--
-- INSERT INTO users(id, address, lat, lon, name, password, secret, email, role_id, status)
-- VALUES (1, null, null, null, 'admin', '$2a$04$8j4Zq6lbQa0dQ8vNajhWLOPyckkC4Uwfpu7f5VBkIFnKn78Jpr0fG', 'admin',
--         'admin@mail.com', 1, 'ACTIVE')